name: peso_mate_getx
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.3 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  auto_size_text: ^3.0.0
  fluttertoast: ^8.0.9
  flutter_slidable: ^1.3.0
  fl_chart: ^0.55.0
  hive_flutter: ^1.1.0
  shared_preferences: ^2.0.15
  animated_text_kit: ^4.2.2
  timezone: ^0.8.0
  rxdart: ^0.27.4
  flutter_native_timezone: ^2.0.0
  flutter_local_notifications: ^9.6.1
  get_storage: ^2.0.3

dev_dependencies: 
  flutter_lints: 2.0.1
  hive_generator: ^1.1.2
  build_runner: ^2.1.11
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

assets:
  - assets/images/No data-pana2.png

fonts:
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa-VariableFont_wght.ttf
    - family: Swera
      fonts:
        - asset: assets/fonts/Swera Italic Demo.otf
    - family: Michroma
      fonts:
        - asset: assets/fonts/DoppioOne-Regular.ttf